Repository fliegwerk/fliegdoc, pull requests merged in 2021-01, with the labels that each got.

#8 feat!: Extract theme into an object passable to the config as `theme`
  .gitattributes
  README.md
  assets/drawio/core-theme-relationship.drawio.png
  src/builders/build-static.ts
  src/index.ts
  src/model/fliegdoc-config.ts
  src/model/index.ts
  src/model/theme.ts
  src/server/index.ts
  src/server/serveDynamic.ts
  src/server/serveStatic.ts
  src/themes/html/index.ts
  src/themes/index.ts
  views/partials/function.eta
Labels: :tulip: enhancement

#10 feat: Search
  src/model/tree.ts
  src/processors/class.ts
  src/processors/function.ts
  src/processors/identifier.ts
  src/processors/init.ts
  src/processors/interface.ts
  src/processors/module.ts
  src/processors/type.ts
  src/processors/variable.ts
  src/themes/html/index.ts
  src/themes/html/serach-index.ts
  views/layout/footer.eta
  views/layout/header.eta
  views/layout/scripts.eta
  views/module.eta
Labels: :tulip: enhancement

#19 refactor(html-theme): Extract `getSearchIndex` into multiple smaller methods
  .eslintrc.js
  src/themes/html/index.ts
  src/themes/html/search-index.ts
  src/themes/html/serach-index.ts
Labels: :tulip: enhancement, ✔ code-climate

#33 refactor: Improve code readability
  src/processors/class.ts
  src/processors/helpers/extractPropertiesAndMethods.ts
  src/processors/helpers/updateJSDocsForStructure.ts
  src/themes/html/createSearchIndexJSON.ts
  src/themes/html/getStaticFileHandler.ts
  src/themes/html/handleLocalImageLink.ts
  src/themes/html/index.ts
  src/themes/html/render.ts
  src/themes/html/searchIndex.ts
  src/themes/html/writeStaticFiles.ts
Labels: :tulip: enhancement

#34 fix: README.MD should reflect NodeJS 10+ support
  README.md
Labels: :books: documentation, :tulip: enhancement
